### ISSUE TITLE
Add CI to repository

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/etf-trace#6]
Add CI for compiling, linting, and clippy-checking the source code on PR.

**Comment by jordens** [comment]
If we merge this into `probe-rs{,-cli}` then we can abandon the repo altogether. I'd prefer that actually.

**Comment by ryan-summers** [comment]
Sounds good - I'll work on migration

**Comment by ryan-summers** [comment]
Closing, no longer needed.
